### PR TITLE
Update readme for alert with Form

### PR DESCRIPTION
**Pull request by zafercuz**
Updated readme when dealing with Form, as DialogButton outside content would result in having the Form validators not working.

### CODE REVIEW

**Comment by ibrahimdevs** [comment]
@zafercuz thanks for your feedback. Can you also add the example form please? 
I think, full working form example will be much better.

**Comment by ibrahimdevs** [comment]
@zafercuz I'm waiting for your contribution. Can you add an example to our project? It will be very helpful for other developers.

**Comment by bynalab** [comment]
Hi @ibrahimdevs, Can you please check the PR list? It has some changes you could merge.

**Comment by ibrahimdevs** [comment]
There is no reply for working example, I'm closing this PR for now.

**Pull request closed without merging**
