### PR TITLE
Added an optional WillPopScope.

### PR DESCRIPTION
**Pull request by fonkamloic**
This will prevent users from poping an alert with back button if need be.

### CODE REVIEW

**Comment by RYOKSEC** [comment]
Thanks a lot i was really going to create this feature as it is very important but i found yours so really thanks ^^

**Comment by RYOKSEC** [comment]
Worked perfectly in my program i suggest you migrate it to master

**Review by RYOKSEC — APPROVED** [review]
Working perfectly

**Comment by ibrahimdevs** [comment]
Thanks for your contribution @fonkamloic  and sorry for my late merge.

**Pull request merged**
