### PR TITLE
Fix: The method 'call' was called on null.

### PR DESCRIPTION
**Pull request by giandifra**
closeFunction cannot be null else there is an exception when it's invoked

```
The following NoSuchMethodError was thrown while handling a gesture:
The method 'call' was called on null.
Receiver: null
Tried calling: call()
```

### CODE REVIEW

**Comment by HugoHeneault** [comment]
Nice one! This seems ready to be merged 👍

**Comment by ibrahimdevs** [comment]
Thanks for your contribution @HugoHeneault  and sorry for my too late merge.

**Comment by HugoHeneault** [comment]
Well that contribution came from @giandifra ! Thanks to him :)

**Comment by ibrahimdevs** [comment]
@giandifra sorry for my confusing, thanks 👍

**Pull request merged**
