### PR TITLE
FIX Bottom Shadow Clipped

### PR DESCRIPTION
**Pull request by rayliverified**
*FIX Remove SingleChildScrollView wrapping AlertDialog to fix shadow clipping.

### CODE REVIEW

**Comment by rayliverified** [comment]
Fixed: 
MaxthonSnap20190821175109

**Comment by rayliverified** [comment]
Any update on this PR?

**Comment by marcos930807** [comment]
please add these

**Comment by lumenier1** [comment]
Have the same problem
flutter-rflutter-alert-shadow-clipped

macOS 10.14.6
iOS simulator 12.2

**Comment by rayliverified** [comment]
Any update? :P

**Comment by ibrahimdevs** [comment]
Thanks for your contribution @searchy2 and sorry for my too late merge.

**Comment by rayliverified** [comment]
Amazing!
Would you be willing to accept a PR that increased text style customization and added customizable padding between the title and description?
I have a local copy of RAlert because of those missing customization options.

**Comment by ibrahimdevs** [comment]
@searchy2 I'm always welcome to new pull requests. Waiting for your new PR 💯 

* I made some improvements, please get the latest version first.

**Pull request merged**
